# Generated by Django 6.0.6 on 2026-06-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postit',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
