# Generated by Django 6.0.6 on 2026-06-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_postit_completada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='color',
            field=models.CharField(choices=[('#2563eb', 'Azul profesional'), ('#7c3aed', 'Morado creativo'), ('#059669', 'Verde progreso'), ('#f97316', 'Naranja urgente'), ('#e11d48', 'Rojo importante')], default='#2563eb', max_length=7),
        ),
    ]
